@echo off
echo Iniciando Entorno Corporativo Multi-Agente (Zero-Node)...
echo Activando entorno virtual...
call .\venv\Scripts\activate.bat
echo Instalando dependencias necesarias (si faltan)...
pip install -r requirements.txt
echo Lanzando API Backend y Dashboard Web...
uvicorn api.main:app --reload --host 127.0.0.1 --port 8000
pause
